SchoolSystem/SchoolSystem/Controllers/RegistroesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Model;
using SchoolSystem.Authorize;

namespace SchoolSystem.Controllers
{
    [CustomAuthorizeAttribute(Perfil = "Administrador")]
    public class RegistroesController : Controller
    {
        private SistemaEscolarEntities db = new SistemaEscolarEntities();

        // GET: Registroes
        public ActionResult Index()
        {
            var registro = db.Registro.Include(r => r.Estudiante);
            return View(registro.ToList());
        }

        // GET: Registroes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Registro registro = db.Registro.Find(id);
            if (registro == null)
            {
                return HttpNotFound();
            }
            return View(registro);
        }

        // GET: Registroes/Create
        public ActionResult Create()
        {
            ViewBag.ID_Estudiante = new SelectList(db.Estudiante, "ID_Estudiante", "Primer_Nombre");
            return View();
        }

        // POST: Registroes/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_Registro,ID_Estudiante,Usuario,Contraseña,Rol")] Registro registro)
        {
            if (ModelState.IsValid)
            {
                db.Registro.Add(registro);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ID_Estudiante = new SelectList(db.Estudiante, "ID_Estudiante", "Primer_Nombre", registro.ID_Estudiante);
            return View(registro);
        }

        // GET: Registroes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Registro registro = db.Registro.Find(id);
            if (registro == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_Estudiante = new SelectList(db.Estudiante, "ID_Estudiante", "Primer_Nombre", registro.ID_Estudiante);
            return View(registro);
        }

        // POST: Registroes/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_Registro,ID_Estudiante,Usuario,Contraseña,Rol")] Registro registro)
        {
            if (ModelState.IsValid)
            {
                db.Entry(registro).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ID_Estudiante = new SelectList(db.Estudiante, "ID_Estudiante", "Primer_Nombre", registro.ID_Estudiante);
            return View(registro);
        }

        // GET: Registroes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Registro registro = db.Registro.Find(id);
            if (registro == null)
            {
                return HttpNotFound();
            }
            return View(registro);
        }

        // POST: Registroes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Registro registro = db.Registro.Find(id);
            db.Registro.Remove(registro);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SchoolSystem/SchoolSystem/Views/Registroes/Create.cshtml
@model Model.Registro

@{
    ViewBag.Title = "Crear";
    Layout = "~/Views/Shared/_InternalHome.cshtml";
}
<style>
    input {
        max-width: 730px !important;
        height: 45px !important;
    }

    select {
        max-width: 730px !important;
        height: 45px !important;
    }
</style>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        <h3 style="margin-left: 45%">Registro</h3>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div style="margin-left: 15%; margin-right: 10%; margin-top: 5%; margin-bottom: 3%">
            <div class="form-group">
                <div class="col-md-12">
                    <div class="input-group input-g">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-cog"></i></span>
                        @Html.DropDownList("ID_Estudiante", null, "--Estudiante/Profesor--", htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.ID_Estudiante, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-12">
                    <div class="input-group input-g">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                        @Html.EditorFor(model => model.Usuario, new { htmlAttributes = new { @class = "form-control", required = "required", placeholder = "Usuario" } })
                        @Html.ValidationMessageFor(model => model.Usuario, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-12">
                    <div class="input-group input-g">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                        @Html.PasswordFor(model => model.Contraseña, new { @class = "form-control", required = "required", placeholder = "Contraseña" })
                        @Html.ValidationMessageFor(model => model.Contraseña, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-12">
                    <div class="input-group input-g">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-cog"></i></span>
                        @Html.DropDownListFor(model => model.Rol, new SelectList(new[] { "Administrador", "Estudiante", "Profesor" }), "--Seleccione el Rol--", new { @class = "form-control", required = "required" })
                        @Html.ValidationMessageFor(model => model.Rol, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="col-xs-12 col-md-6 ">
                @Html.ActionLink("Cancelar", "Index", "Registroes", null, new { @style = "max-width: 450px !important; height: 45px !important", @class = "btn btn-primary btn-block" })
            </div>

            <div class="col-xs-12 col-md-6">
                <input type="submit" value="Guardar" class="btn btn-danger btn-block" />
            </div>

        </div>
    </div>

}

SchoolSystem/SchoolSystem/Views/Registroes/Delete.cshtml
@model Model.Registro

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Registro</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Usuario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Usuario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Contraseña)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contraseña)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rol)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rol)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estudiante.Primer_Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estudiante.Primer_Nombre)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SchoolSystem/SchoolSystem/Views/Registroes/Details.cshtml
@model Model.Registro

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_InternalHome.cshtml";
}

<h2>Detalles</h2>

<div>
    <h4>Registro</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Usuario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Usuario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Contraseña)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contraseña)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rol)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rol)
        </dd>

        <dt>
            @Html.DisplayName("Primer Nombre")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estudiante.Primer_Nombre)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.ID_Registro }, new { @class = "btn btn-success btn-large" }) |
    @Html.ActionLink("Volver", "Index", null, new { @class = "btn btn-danger btn-large" })
</p>

SchoolSystem/SchoolSystem/Views/Registroes/Edit.cshtml
@model Model.Registro

@{
    ViewBag.Title = "Editar";
    Layout = "~/Views/Shared/_InternalHome.cshtml";
}
<style>
    input {
        max-width: 730px !important;
        height: 45px !important;
    }

    select {
        max-width: 730px !important;
        height: 45px !important;
    }
</style>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h3 style="margin-left: 45%"> Editar</h3>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID_Registro)

        <div style="margin-left: 15%; margin-right: 10%; margin-top: 5%; margin-bottom: 3%">
            <div class="form-group">
                <div class="col-md-12">
                    <div class="input-group input-g">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-cog"></i></span>
                        @Html.DropDownList("ID_Estudiante", null, "--Estudiante/Profesor--", htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.ID_Estudiante, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-12">
                    <div class="input-group input-g">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                        @Html.EditorFor(model => model.Usuario, new { htmlAttributes = new { @class = "form-control", required = "required", placeholder = "Usuario" } })
                        @Html.ValidationMessageFor(model => model.Usuario, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-12">
                    <div class="input-group input-g">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                        @Html.PasswordFor(model => model.Contraseña, new { @class = "form-control", required = "required", placeholder = "Contraseña" })
                        @Html.ValidationMessageFor(model => model.Contraseña, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-12">
                    <div class="input-group input-g">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-cog"></i></span>
                        @Html.DropDownListFor(model => model.Rol, new SelectList(new[] { "Administrador", "Estudiante", "Profesor" }), "--Seleccione el Rol--", new { @class = "form-control", required = "required" })
                        @Html.ValidationMessageFor(model => model.Rol, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="col-xs-12 col-md-6 ">
                @Html.ActionLink("Cancelar", "Index", "Registroes", null, new { @style = "max-width: 450px !important; height: 45px !important", @class = "btn btn-primary btn-block" })
            </div>

            <div class="col-xs-12 col-md-6">
                <input type="submit" value="Guardar" class="btn btn-danger btn-block" />
            </div>

        </div>
    </div>

}

SchoolSystem/SchoolSystem/Views/Registroes/Index.cshtml
@model IEnumerable<Model.Registro>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_InternalHome.cshtml";
}
    <div class="text-info">
        @Html.ActionLink("Asignar Usuario", "Create", null, new { @class = "btn btn-danger btn-large" })
    </div>
<br />
<br />
<h2>Lista de Usuarios</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Usuario)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Contraseña)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Rol)
        </th>
        <th>
            @Html.DisplayName("Primer Nombre")
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Usuario)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Contraseña)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rol)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Estudiante.Primer_Nombre)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", null, new { id = item.ID_Registro}, new { id = item.ID_Registro, @class = "btn btn-primary btn-large" }) |
                @Html.ActionLink("Detalles", "Details", null,  new { id = item.ID_Registro}, new { @class = "btn btn-success btn-large" }) |

            </td>
        </tr>
    }

</table>