SchoolSystem/SchoolSystem/Controllers/AdmisionesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using Model;

namespace SchoolSystem.Controllers
{
    public class AdmisionesController : Controller
    {
        private SistemaEscolarEntities db = new SistemaEscolarEntities();

        public ActionResult InfoAdmi()
        {
            return View();
        }

        // GET: Admisiones/Create
        public ActionResult Create()
        {
            ViewBag.ID_Grado = new SelectList(db.Grado, "ID_Grado", "Descripcion");
            return View();
        }

        // POST: Admisiones/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_Estudiante,Primer_Nombre,Segundo_Nombre,Primer_Apellido," +
            "Segundo_Apelido,FechaNacimiento,Edad,Nacionalidad,Sexo,ID_Grado,CentroEducativo," +
            "GradoSolicita,DistritoEducativo")] Estudiante estudiante, [Bind(Include = "Calle,Provincia,Municipio," +
            "Sector,No_Casa")] Direccion direccion, [Bind(Include = "Nombres,Apellidos," +
            "Parentesco,Cedula,Profesion,Telefono,Celular")] Padre_Tutor padre, [Bind(Include = "ID_Estudiante")]
            Documentos_Estudiantes documentos, HttpPostedFileBase imagen)
        {
            if (ModelState.IsValid)
            {
                documentos.Foto = new byte[imagen.ContentLength];
                imagen.InputStream.Read(documentos.Foto, 0, imagen.ContentLength);
                documentos.ActaNacimiento = new byte[imagen.ContentLength];
                imagen.InputStream.Read(documentos.ActaNacimiento, 1, imagen.ContentLength);
                documentos.CertificadoMedico = new byte[imagen.ContentLength];
                imagen.InputStream.Read(documentos.CertificadoMedico, 2, imagen.ContentLength);
                documentos.CopiaCedula = new byte[imagen.ContentLength];
                imagen.InputStream.Read(documentos.CopiaCedula, 3, imagen.ContentLength);
                documentos.CertificadoEscorlar = new byte[imagen.ContentLength];
                imagen.InputStream.Read(documentos.CertificadoEscorlar, 4, imagen.ContentLength);
                documentos.RecordNotas = new byte[imagen.ContentLength];
                imagen.InputStream.Read(documentos.RecordNotas, 5, imagen.ContentLength);

                direccion.ID_Estudiante = estudiante.ID_Estudiante;
                padre.ID_Estudiante = estudiante.ID_Estudiante;
                documentos.ID_Estudiante = estudiante.ID_Estudiante;
                db.Estudiante.Add(estudiante);
                db.Direccion.Add(direccion);
                db.Padre_Tutor.Add(padre);
                db.Documentos_Estudiantes.Add(documentos);
                db.SaveChanges();
                return RedirectToAction("InfoAdmi");
            }

            ViewBag.ID_Grado = new SelectList(db.Grado, "ID_Grado", "Descripcion", estudiante.ID_Grado);
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SchoolSystem/SchoolSystem/Controllers/Asignar_TareaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Model;

namespace SchoolSystem.Controllers
{
    public class Asignar_TareaController : Controller
    {
        private SistemaEscolarEntities db = new SistemaEscolarEntities();

        // GET: Asignar_Tarea
        public ActionResult Index()
        {
            var asignar_Tarea = db.Asignar_Tarea.Include(a => a.Materias);
            return View(asignar_Tarea.ToList());
        }

        public ActionResult Español()
        {
            var asignar_Tarea = db.Asignar_Tarea.Include(a => a.Materias);
            var consulta = from x in db.Asignar_Tarea where x.ID_Materia == 1 select x;
            return View(consulta.ToList());
        }

        public ActionResult Matematica()
        {
            var asignar_Tarea = db.Asignar_Tarea.Include(a => a.Materias);
            var consulta = from x in db.Asignar_Tarea where x.ID_Materia == 2 select x;
            return View(consulta.ToList());
        }

        public ActionResult Sociales()
        {
            var asignar_Tarea = db.Asignar_Tarea.Include(a => a.Materias);
            var consulta = from x in db.Asignar_Tarea where x.ID_Materia == 3 select x;
            return View(consulta.ToList());
        }

        public ActionResult Naturales()
        {
            var asignar_Tarea = db.Asignar_Tarea.Include(a => a.Materias);
            var consulta = from x in db.Asignar_Tarea where x.ID_Materia == 4 select x;
            return View(consulta.ToList());
        }

        public ActionResult Religion()
        {
            var asignar_Tarea = db.Asignar_Tarea.Include(a => a.Materias);
            var consulta = from x in db.Asignar_Tarea where x.ID_Materia == 5 select x;
            return View(consulta.ToList());
        }

        public ActionResult Deporte()
        {
            var asignar_Tarea = db.Asignar_Tarea.Include(a => a.Materias);
            var consulta = from x in db.Asignar_Tarea where x.ID_Materia == 6 select x;
            return View(consulta.ToList());
        }

        public ActionResult Arte()
        {
            var asignar_Tarea = db.Asignar_Tarea.Include(a => a.Materias);
            var consulta = from x in db.Asignar_Tarea where x.ID_Materia == 7 select x;
            return View(consulta.ToList());
        }

        public ActionResult Optativa()
        {
            var asignar_Tarea = db.Asignar_Tarea.Include(a => a.Materias);
            var consulta = from x in db.Asignar_Tarea where x.ID_Materia == 8 select x;
            return View(consulta.ToList());
        }

        // GET: Asignar_Tarea/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Asignar_Tarea asignar_Tarea = db.Asignar_Tarea.Find(id);
            if (asignar_Tarea == null)
            {
                return HttpNotFound();
            }
            return View(asignar_Tarea);
        }

        // GET: Asignar_Tarea/Create
        public ActionResult Create(int id)
        {
            ViewBag.ID_Materia = id;
            return View();
        }

        // POST: Asignar_Tarea/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Asignar_Tarea asignar_Tarea, int id)
        {
            if (ModelState.IsValid)
            {
                db.Asignar_Tarea.Add(new Asignar_Tarea
                {
                    ID_AsignarTarea = asignar_Tarea.ID_AsignarTarea,
                    ID_Materia = id,
                    Titulo =  asignar_Tarea.Titulo,
                    Contenido = asignar_Tarea.Contenido
                });
                db.SaveChanges();
                ViewBag.id = asignar_Tarea.ID_AsignarTarea;
                return RedirectToAction("Index");
            }

            ViewBag.ID_Materia = id;
            return View(asignar_Tarea);
        }

        // GET: Asignar_Tarea/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Asignar_Tarea asignar_Tarea = db.Asignar_Tarea.Find(id);
            if (asignar_Tarea == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_Materia = new SelectList(db.Materias, "ID_Materia", "Descripcion", asignar_Tarea.ID_Materia);
            return View(asignar_Tarea);
        }

        // POST: Asignar_Tarea/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_AsignarTarea,ID_Materia,Titulo,Contenido")] Asignar_Tarea asignar_Tarea)
        {
            if (ModelState.IsValid)
            {
                db.Entry(asignar_Tarea).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ID_Materia = new SelectList(db.Materias, "ID_Materia", "Descripcion", asignar_Tarea.ID_Materia);
            return View(asignar_Tarea);
        }

        // GET: Asignar_Tarea/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Asignar_Tarea asignar_Tarea = db.Asignar_Tarea.Find(id);
            if (asignar_Tarea == null)
            {
                return HttpNotFound();
            }
            return View(asignar_Tarea);
        }

        // POST: Asignar_Tarea/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Asignar_Tarea asignar_Tarea = db.Asignar_Tarea.Find(id);
            db.Asignar_Tarea.Remove(asignar_Tarea);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SchoolSystem/SchoolSystem/Controllers/LoginController.cs
using Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace SchoolSystem.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Account(string message ="")
        {
            ViewBag.Message = message;
            return View();
        }

        [HttpPost]
        public ActionResult Account(string usuario, string contraseña)
        {
            if(!string.IsNullOrEmpty(usuario) && !string.IsNullOrEmpty(contraseña))
            {
                SistemaEscolarEntities db = new SistemaEscolarEntities();
                var user = db.Registro.FirstOrDefault(e => e.Usuario == usuario && e.Contraseña == contraseña);
                //si el usuario es diferente a null
                if(user!=null)
                {
                    //usuario con datos
                    FormsAuthentication.SetAuthCookie(user.Usuario, true);
                    Session["Usuario"] = user.Usuario;
                    Session["ID"] = user.ID_Registro;
                    Session["Estudiante"] = user.Estudiante;
                    Session["ID_Estudiante"] = user.ID_Estudiante;
                    Session["Rol"] = user.Rol;
                    return RedirectToAction("InternalHome", "Home");
                    
                }
                else
                {
                    return RedirectToAction("Account", new { message = "Datos no encontrados" });
                }
            }
            else
            {
                return Account("Llena todos los campos para iniciar sesion");
            }
        }
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Account");
        }
    }
}

SchoolSystem/SchoolSystem/Controllers/ServiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Rotativa;
using Rotativa.Options;
using Model;
using System.Web.Services.Description;

namespace SchoolSystem.Controllers
{

    public class ServiceController : Controller
    {
        SistemaEscolarEntities db = new SistemaEscolarEntities();

        // GET: Service
        public ActionResult Index(string message = "")
        {
            ViewBag.Message = message;
            return View();
        }

        public ActionResult RecordNotas(string PrimerNombre, string PrimerApellido, string SegundoApellido, string NombrePadres, string Year)
        {
            var Id =  db.Calificaciones.FirstOrDefault();

            var Student = db.Calificaciones.ToList().Where(x => x.Estudiante.Primer_Nombre == PrimerNombre && x.Estudiante.Primer_Apellido == PrimerApellido && x.Estudiante.Segundo_Apelido == SegundoApellido && x.Id_Estudiante == x.Estudiante.ID_Estudiante);
            var Calification = db.Calificaciones.FirstOrDefault(x => x.Id_Estudiante.ToString() == Id.Id_Estudiante.ToString());
            var Nombre = Calification.Estudiante.Primer_Nombre + " " + Calification.Estudiante.Primer_Apellido + " " + Calification.Estudiante.Segundo_Apelido;

            ViewBag.Nombre = Nombre;
            ViewBag.Student = Student;

            if (Calification == null)
            {
                return RedirectToAction("Index", new { message = "No Existe este registro, favor ingrese valores validos" });
            }
            else
            {
                return View();
            }


        }



        public ActionResult Print()
        {
            return new ActionAsPdf("RecordNotas") { FileName = "RecordNotas.pdf" };
        }


    }

}

SchoolSystem/SchoolSystem/Views/Shared/Lista_Materias.cshtml
<style>
    .panel-heading {
        color: #fff !important;
        background-color: #22233e !important;
    }
</style>
<div class="panel panel-default">
    <div class="panel-heading text-center">Materias</div>
    <div class="panel-body">
        <div class="row" style="margin-bottom: 50px">
            <div class="col-xs-12 col-md-3">
                <div class="thumbnail" style="height: 200px; background-color: #61C187;">

                    <div style="margin-top: 40px;">
                        <div style="margin-top: 20px; margin-bottom: 6px">
                            @Html.ActionLink("Lengua Española", "Español", "Asignar_Tarea", new { }, new { @class = "btn btn-default btn-block" })
                        </div>
                        <div class="img-responsive">

                            <img src="~/Image/jerry-wang-jfnUC7s3iuw-unsplash.jpg" class="img-circle center-block" height="100" width="100" />
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-xs-12 col-md-3">
                <div class="thumbnail" style="height: 200px; background-color: #61C187;">

                    <div style="margin-top: 40px;">
                        <div style="margin-top: 20px; margin-bottom: 6px">
                            @Html.ActionLink("Matemáticas", "Matematica", "Asignar_Tarea", new { }, new { @class = "btn btn-default btn-block" })
                        </div>
                        <div class="img-responsive">

                            <img src="~/Image/jerry-wang-jfnUC7s3iuw-unsplash.jpg" class="img-circle center-block" height="100" width="100" />
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-xs-12 col-md-3">
                <div class="thumbnail" style="height: 200px; background-color: #61C187;">

                    <div style="margin-top: 40px;">
                        <div style="margin-top: 20px; margin-bottom: 6px">
                            @Html.ActionLink("Ciencias Naturales", "Naturales", "Asignar_Tarea", new { }, new { @class = "btn btn-default btn-block" })
                        </div>
                        <div class="img-responsive">

                            <img src="~/Image/jerry-wang-jfnUC7s3iuw-unsplash.jpg" class="img-circle center-block" height="100" width="100" />
                        </div>
                    </div>
                </div>
            </div>


            <div class="col-xs-12 col-md-3">
                <div class="thumbnail" style="height: 200px; background-color: #61C187;">

                    <div style="margin-top: 40px;">
                        <div style="margin-top: 20px; margin-bottom: 6px">
                            @Html.ActionLink("Ciencias Sociales", "Sociales", "Asignar_Tarea", new { }, new { @class = "btn btn-default btn-block" })
                        </div>
                        <div class="img-responsive">

                            <img src="~/Image/jerry-wang-jfnUC7s3iuw-unsplash.jpg" class="img-circle center-block" height="100" width="100" />
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-12 col-md-3">
                <div class="thumbnail" style="height: 200px; background-color: #61C187;">

                    <div style="margin-top: 40px;">
                        <div style="margin-top: 20px; margin-bottom: 6px">
                            @Html.ActionLink("Formación Humana Religiosa", "Religion", "Asignar_Tarea", new { }, new { @class = "btn btn-default btn-block" })
                        </div>
                        <div class="img-responsive">

                            <img src="~/Image/jerry-wang-jfnUC7s3iuw-unsplash.jpg" class="img-circle center-block" height="100" width="100" />
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-xs-12 col-md-3">
                <div class="thumbnail" style="height: 200px; background-color: #61C187;">

                    <div style="margin-top: 40px;">
                        <div style="margin-top: 20px; margin-bottom: 6px">
                            @Html.ActionLink("Educación Física", "Deporte", "Asignar_Tarea", new { }, new { @class = "btn btn-default btn-block" })
                        </div>
                        <div class="img-responsive">

                            <img src="~/Image/jerry-wang-jfnUC7s3iuw-unsplash.jpg" class="img-circle center-block" height="100" width="100" />
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-xs-12 col-md-3">
                <div class="thumbnail" style="height: 200px; background-color: #61C187;">

                    <div style="margin-top: 40px;">
                        <div style="margin-top: 20px; margin-bottom: 6px">
                            @Html.ActionLink("Educación Artística", "Arte", "Asignar_Tarea", new { }, new { @class = "btn btn-default btn-block" })
                        </div>
                        <div class="img-responsive">

                            <img src="~/Image/jerry-wang-jfnUC7s3iuw-unsplash.jpg" class="img-circle center-block" height="100" width="100" />
                        </div>
                    </div>
                </div>
            </div>


            <div class="col-xs-12 col-md-3">
                <div class="thumbnail" style="height: 200px; background-color: #61C187;">

                    <div style="margin-top: 40px;">
                        <div style="margin-top: 20px; margin-bottom: 6px">
                            @Html.ActionLink("Curso Optativo", "Optativa", "Asignar_Tarea", new { }, new { @class = "btn btn-default btn-block" })
                        </div>
                        <div class="img-responsive">

                            <img src="~/Image/jerry-wang-jfnUC7s3iuw-unsplash.jpg" class="img-circle center-block" height="100" width="100" />
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

SchoolSystem/SchoolSystem/Views/Shared/MenuProfesores.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <title>InternalHome</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar nav-custom navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">Logo</a>
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#"><span class="glyphicon glyphicon-user"></span> @Session["Usuario"]</a></li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li><a href="/Login/Logout"><span class="glyphicon glyphicon-log-in"></span> Cerrar Sesión</a></li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="row" style="margin-top: 8%">
        <div class="col-md-3">
            <div class="list-group" style="position:fixed; width:22%">
                <a href="/Home/InternalHome" class="list-group-item height">  <span class="glyphicon glyphicon-home"></span> Inicio</a>
                <a href="/Materias/Index" class="list-group-item height"> <span class="glyphicon glyphicon-book"></span> Materias</a>
                <a href="/Asignar_Tarea/Index" class="list-group-item height"><span class="glyphicon glyphicon-list-alt"></span> Asignaciones</a>
                <a href="/Subir_Tarea/Index" class="list-group-item height"><span class="glyphicon glyphicon-list-alt"></span> Entrega Asignaciones</a>
                <a href="/Materias/Calificacion" class="list-group-item height"><span class="glyphicon glyphicon-ok"></span> Calificaciones</a>
                <a href="/Registroes/Index" class="list-group-item height"><span class="glyphicon glyphicon-ok"></span> Registro(Adm)</a>
            </div>
        </div>
        <div class="container body-content col-md-9">
            @RenderBody()
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

</body>
</html>
<script src="~/Scripts/jquery-3.4.1.js"></script>
<script src="~/Scripts/bootstrap.js"></script>

SchoolSystem/SchoolSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/css/template.css" rel="stylesheet" />
    <title>@ViewBag.Title Inicio</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="row">
        <div class="col-xs-5 col-sm-5 col-md-6 col-md-push-1">
            <img src="~/Image/school.png" height="120" />
        </div>
        <div class="col-xs-6 col-sm-5 col-md-5 ">
            <div class="repDom"></div>
            <div class="pSearch">
                <!--[COLOCAR BUSCADOR EN ESTA PARTE]-->
                <div class="search">
                    <form>
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Search">
                            <div class="input-group-btn">
                                <button class="btn btn-default" type="submit">
                                    <i class="glyphicon glyphicon-search"></i>
                                </button>
                            </div>
                        </div>
                    </form>
                </div><!--end search-->
            </div><!--end pSearch-->
            <div class="navMenu">
                <!--[COLOCAR EN ESTA PARTE EL MENU DE NAVEGACION FACIL]-->
                <ul class="menu">
                    <li><a href="@Url.Action("Index","Home")">Inicio</a></li>
                    <li><a href="@Url.Action("About","Home")">Mapa de sitio</a></li>
                    <li><a href="@Url.Action("Contact","Home")">Contacto</a></li>
                </ul><!--end menu-->
            </div><!--end navMenu-->
        </div><!--end headerBoxBox1-->
    </div>
    <div>
        <div class="navbar nav-custom ">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav ">
                        <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                        <li>@Html.ActionLink("Sobre Nostros", "Contact", "Home")</li>

                        <li class="treeview">
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                Admisiones
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li> @Html.ActionLink("Requisitos admisión", "InfoAdmi", "Admisiones")</li>
                                <li> @Html.ActionLink("Solicitud admisión", "Create", "Admisiones")</li>
                            </ul>
                        </li>

                        <li class="treeview">
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                Servicios
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Solicitar Record de Notas", "Index", "Service")</li>
                              
                            </ul>
                        </li>
                        <li>@Html.ActionLink("Transparencia", "Transparecia", "Home")</li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="#"><span class="glyphicon glyphicon-log-in"></span></a></li>
                        <li>@Html.ActionLink("Iniciar Sesión", "Account", "Login")</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class=" body-content">
        @RenderBody()
        <footer class="color-footer text-color-footer" style="padding-top: 10px;padding-bottom: 10px">
            <ul id="linesLogos">
                <li id="logo1"><img src="~/Image/school-logo.png" class="img-responsive"/></li><!--[SUSTITUIR LA IMAGEN "logoFooter1.gif" POR EL LOGO DE LA INSTITUION]-->
                <li id="logo2"><img src="~/Image/1200px-Coat_of_arms_of_the_Dominican_Republic.svg.png" class="img-responsive" /> </li><!--[ESTE ES EL ESCUDO DE LA REPUBLICA DOMINICANA]-->
            </ul><!--end linesLogos-->

            <ul class="text-center">
                <li id="space">&nbsp;</li>
                <li>
                    <a href="#">Escuela David Durán  </a><!--[ESPECIFICAR LA RUTA AL INICIO DEL PORTAL]--><br>
                    Avenida Máximo Gómez esquina Santiago, No.02 Gazcue, Distrito Nacional, República Dominicana.<br>
                    Tel.:8092312774 | email: <a href="mailto:infoescueladavidduran@gmail.com">infoescueladavidduran@gmail.com</a><br>
                    <span>&copy; @DateTime.Now.Year Todos los Derechos Reservados</span>
                </li><!--end info-->
            </ul><!--end infoFooter-->
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>